name: .NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup SQL Server (choco)
      shell: pwsh
      run: |
          choco install sql-server-express --no-progress

    - name: Setup PostgreSQL (choco)
      shell: pwsh
      run: |
          choco install postgresql13 --no-progress --params '/Password:root'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release "-p:Version=1.0.${{ github.run_number }}" "-p:PackageVersion=1.0.${{ github.run_number }}"
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Push to nuget.org
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json